### ISSUE TITLE
Netdaemon doesnt register the installed companion app in HACS

### ISSUE THREAD

**Issue by danniewalden** [net-daemon/integration#45]
## The problem
I have installed the companion app (v 22.02.0) via HACS, however, when i run my netdaemon it tells me the companion is not installed:

![image](https://user-images.githubusercontent.com/7082138/149019612-691ca6a2-5a2e-4be4-b4f4-e29ee646eb01.png)

I have in my code, registered a simple dummy callback, and tried to call that callback via the developer service call dialog, but it cannot find it. 

I cannot find any setup on the companion app in the docs, beyond installing it via HACS, so i think i've done all setup according to the docs.

## System Health

version | core-2021.12.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.83
arch | x86_64
timezone | Europe/Copenhagen

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4998
Installed Version | 1.19.3
Stage | running
Available Repositories | 934
Downloaded Repositories | 17

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | failed to load: timeout

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.0
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 30.8 GB
disk_used | 17.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (3.7.0), Google Assistant SDK (2.5.0), Terminal & SSH (9.1.3), File editor (5.3.3), Node-RED (9.2.1), Portainer (1.5.1), Duck DNS (1.13.0), Let's Encrypt (4.11.0), Z-Wave JS to MQTT (0.33.0), Samba share (9.5.1), Z-Wave JS (0.1.52), AdGuard Home (4.1.9), NetDaemon (22.01.0), C# (0.10.0), Mosquitto broker (6.0.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 5
-- | --
resources | 7
views | 4
mode | storage

</details>

## Traceback/Error logs

```txt

```

**Comment by ludeeus** [comment]
You need to configure it as well <https://github.com/net-daemon/integration#installation>

**Comment by danniewalden** [comment]
Ugh, sorry, GH doesnt send me email on responses.

I misread the bulletpoint number 4 (configuration part) - thanks a lot. And thanks for a great plugin :) 👍
